---
- hosts: all
  tasks:
    - name: update apt cache
      apt: update_cache=yes
      become: True

    - name: install git
      apt: name=git
      become: True

    - name: install rbenv
      git: repo=https://github.com/sstephenson/rbenv.git
           dest=~/.rbenv
           update=no

    - name: install ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git
           dest=~/.rbenv/plugins/ruby-build
           update=no

    - name: create bash_profile
      copy: src=files/bash_profile dest=~/.bash_profile

    - name: install ruby dependencies
      apt: name={{ item }}
      with_items:
        - libssl-dev
        - libreadline-dev
        - zlib1g-dev
      become: True

    - name: install ruby 2.2.3
      shell: . ~/.bash_profile && rbenv install -s 2.2.3

    - name: set global ruby to 2.2.3
      shell: . ~/.bash_profile && rbenv global 2.2.3

    - name: install rails dependencies
      apt: name={{ item }}
      with_items:
        - libsqlite3-dev
      become: True

    - name: install rails gem
      shell: . ~/.bash_profile && gem install rails

    - name: get nodejs repository script
      get_url: url=https://deb.nodesource.com/setup_5.x dest=/tmp/setup_5.x

    - name: add nodejs repository
      command: bash /tmp/setup_5.x
      become: True

    - name: install nodejs
      apt: name={{ item }}
      with_items:
        - build-essential
        - nodejs
      become: True
